# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'My-Config'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["puchi_ble_v1"]'
      shield: '["humla"]'
      alphas: '["qwerty"]'  # Correct field for keymap
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR", "#define MIRYOKU_CLIPBOARD_MAC"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y", "CONFIG_ZMK_CLIPBOARD_MAC=y"]'
      branches: '["petejohanson/zmk/feat/pointers-move-scroll","zmkfirmware/zmk/main petejohanson/zmk/feat/pointers-move-scroll"]'
