# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example mousekeyspr for Puchi BLE with Clipboard and Tap Delay'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["puchi_ble_v1"]'
      shield: '["humla"]'
      keymap: '["qwerty"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR", "#define MIRYOKU_CLIPBOARD_MAC", "#define MIRYOKU_KLUDGE_TAPDELAY"]'
      branches: '["petejohanson/zmk/feat/pointers-move-scroll","zmkfirmware/zmk/main petejohanson/zmk/feat/pointers-move-scroll"]'
